"""empty message

Revision ID: 595dd1032f30
Revises: c324f5a798aa
Create Date: 2025-05-07 11:40:53.494092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595dd1032f30'
down_revision = 'c324f5a798aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'post_id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    # ### end Alembic commands ###
